libraries = [
    "libyokan-bedrock-module.so",
    "libflock-bedrock-module.so"
]

[margo]
use_progress_thread = true

  [[margo.argobots.pools]]
  name = "my_pool_1"
  kind = "fifo_wait"
  access = "mpmc"

  [[margo.argobots.pools]]
  name = "my_pool_2"
  kind = "fifo_wait"
  access = "mpmc"

[[providers]]
name = "my_provider_1"
type = "yokan"
provider_id = 1
  [providers.config.database]
  type = "map"

[[providers]]
name = "my_provider_2"
type = "flock"
provider_id = 2
  [providers.config]
  bootstrap = ["join", "mpi"]
  group = { "type" = "centralized" }
  file = "distributed_service.flock"
